== 공동배달

=== 공동배달 장바구니 추가
operation::joint-deliveries/carts/create[snippets='http-request,path-parameters,request-fields']

=== 공동배달 장바구니 삭제
operation::joint-deliveries/carts/delete[snippets='http-request,path-parameters']

=== 공동배달 장바구니 목록 조회
operation::joint-deliveries/carts/list[snippets='http-request,path-parameters,response-fields']

=== 공동배달 모집 생성
operation::joint-deliveries/create[snippets='http-request,request-fields']

=== 공동배달 모집 취소
operation::joint-deliveries/delete[snippets='http-request,path-parameters']

=== 공동배달 상세 조회
operation::joint-deliveries/detail[snippets='http-request,path-parameters,response-fields']

=== 공동배달 목록 조회
operation::joint-deliveries/list[snippets='http-request,query-parameters,response-fields']

=== 메뉴 목록 조회
operation::joint-deliveries/menus[snippets='http-request,path-parameters,response-fields']

=== 공동배달 수령 확인
operation::joint-deliveries/receive[snippets='http-request,path-parameters']

=== 가게 목록 조회
operation::joint-deliveries/stores[snippets='http-request,query-parameters,response-fields']